import Dashboard from './Dashboard'
import SessionManagement from './SessionManagement'
import StudyManagement from './StudyManagement'
import UserManagement from './UserManagement'
import GroupManagement from './GroupManagement'
import CenterManagement from './CenterManagement'
import WelcomePage from './WelcomePage'
import { DataPurge } from './DataPurge'
import ReportTemplate from './ReportTemplate'
import AuditTrail from './AuditTrail'
import Alerts from './Alerts'

